#!/usr/bin/env python

from gettext import gettext as _

import gobject
import gtk
import pango
import webkit

class BrowserPage(webkit.WebView):

  def __init__(self):
    webkit.WebView.__init__(self)
    settings = self.get_settings()
    settings.set_property('enable-developer-extras', False)
    settings.set_property('enable-default-context-menu', False)

    settings.set_property('default-encoding', 'utf-8')
    settings.set_property('enable-private-browsing', True)
    settings.set_property('enable-html5-local-storage', False)
    
    settings.set_property('enable-plugins', False)

    # scale other content besides from text as well
    self.set_full_content_zoom(True)
    
class TabLabel(gtk.HBox):
  """A class for Tab labels"""
  
  __gsignals__ = {
    'close': (gobject.SIGNAL_RUN_FIRST, gobject.TYPE_NONE, (gobject.TYPE_OBJECT,))
  }

  def __init__(self, title, scrolled_window):
    """initialize the tab label"""
    
    gtk.HBox.__init__(self, False, 4)
    self.title = title
    self.scrolled_window = scrolled_window
    self.label = gtk.Label(title)
    self.label.props.max_width_chars = 30
    self.label.set_ellipsize(pango.ELLIPSIZE_MIDDLE)
    self.label.set_alignment(0.0, 0.5)

    close_image = gtk.image_new_from_stock(gtk.STOCK_CLOSE, gtk.ICON_SIZE_MENU)
    close_button = gtk.Button()
    close_button.set_relief(gtk.RELIEF_NONE)
    close_button.set_image(close_image)
    close_button.connect('clicked', lambda x: self.emit('close', self.scrolled_window))

    self.pack_start(self.label, True, True, 0)
    self.pack_start(close_button, False, False, 0)

    self.connect('style-set', self._tab_label_style_set)

  def _tab_label_style_set(self, tab_label, style):
    context = tab_label.get_pango_context()
    metrics = context.get_metrics(tab_label.style.font_desc, context.get_language())
    char_width = metrics.get_approximate_digit_width()
    (width, height) = gtk.icon_size_lookup(gtk.ICON_SIZE_MENU)
    tab_label.set_size_request(10 * pango.PIXELS(char_width) + 2 * width,
pango.PIXELS(metrics.get_ascent() + metrics.get_descent()) + 4)

class ContentPane(gtk.Notebook):

  __gsignals__ = {
    'focus-entry': (gobject.SIGNAL_RUN_FIRST, gobject.TYPE_NONE, ()),
	'update-title': (gobject.SIGNAL_RUN_FIRST, gobject.TYPE_NONE, (gobject.TYPE_OBJECT, gobject.TYPE_STRING, gobject.TYPE_STRING)),
    }

  def __init__(self):
    """initialize the content pane"""
    gtk.Notebook.__init__(self)
    self.props.scrollable = True
    self.props.homogeneous = True
    self.set_show_border(False)
    self.connect('switch-page', self._switch_page)

    self.show_all()
    self._hovered_uri = None
    
  def new_tab(self, url = None, show_new = True, web_view = None):
    """Creates a new page in a new tab"""
    
    if web_view:
      browser = web_view
    else: 
      browser = BrowserPage()

    scrolled_window = gtk.ScrolledWindow()
    scrolled_window.props.hscrollbar_policy = gtk.POLICY_AUTOMATIC
    scrolled_window.props.vscrollbar_policy = gtk.POLICY_AUTOMATIC
    scrolled_window.title = None
    scrolled_window.url = None
    
    browser.connect('title-changed', self._title_changed, scrolled_window)
    browser.connect('load-committed', self._url_changed, scrolled_window)
    browser.connect('load-finished', self._load_finished, scrolled_window)
    browser.connect('hovering-over-link', self._hovering_over_link)

	# no file chooser
    browser.connect('run-file-chooser', returntrue)

	# no file transfering
    browser.connect('download-requested', returntrue)

	# no printing
    browser.connect('print-requested', returntrue)

    browser.connect('create-web-view', self._new_web_view_request)
    browser.connect('button-press-event', self._on_button_press_event)
      
    scrolled_window.add(browser)
    scrolled_window.show_all()
    
    label = TabLabel(url, scrolled_window)
    label.connect('close', self.close_tab)
    label.show_all()
    
    new_tab_number = self.append_page(scrolled_window, label)
    self.set_tab_label_packing(scrolled_window, False, True, gtk.PACK_START)
    self.set_tab_label(scrolled_window, label)
    
    self.set_show_tabs(self.get_n_pages() > 1)
    self.show_all()
    
    if url:
      scrolled_window.url = url
      browser.load_uri(url)
    else:
      scrolled_window.title = "New Tab"
      scrolled_window.url = ""
      label.label.set_label("New Tab")
    	
    if show_new:
	  self.set_current_page(new_tab_number)
	  if not url:
	    self.emit('focus-entry')
    	
  def close_tab(self, label, scrolled_window):
    page_num = self.page_num(scrolled_window)
    if page_num != -1:
      browser = scrolled_window.get_child()
      browser.destroy()
      self.remove_page(page_num)
    self.set_show_tabs(self.get_n_pages() > 1)
    
  def close_current_tab(self):
	if (self.get_n_pages() > 1):
		self.close_tab(None, self.get_nth_page(self.get_current_page()))

  def go_back(self):
    child = self.get_nth_page(self.get_current_page())
    view = child.get_child()
    view.go_back()

  def go_forward(self):
    child = self.get_nth_page(self.get_current_page())
    view = child.get_child()
    view.go_forward()

  def refresh(self):
    child = self.get_nth_page(self.get_current_page())
    view = child.get_child()
    view.reload()

  def zoom_in(self):
    """Zoom into the page"""
    child = self.get_nth_page(self.get_current_page())
    view = child.get_child()
    view.zoom_in()

  def zoom_out(self):
    """Zoom out of the page"""
    child = self.get_nth_page(self.get_current_page())
    view = child.get_child()
    view.zoom_out()
    
  def load (self, text):
    """Load the given uri in the current web view"""
    
    child = self.get_nth_page(self.get_current_page())
    view = child.get_child()
    view.open(text)
    
  def _on_button_press_event(self, widget, event):
    if event.type == gtk.gdk.BUTTON_PRESS and self._hovered_uri:
      if event.button == 2:
        self.new_tab(self._hovered_uri, False)
        return True
    
  def _hovering_over_link(self, view, title, uri):
    self._hovered_uri = uri
    
  def _switch_page(self, notebook, page, page_num):
    scrolled_window = self.get_nth_page(page_num)
    self._update_app(scrolled_window)
    
  def _new_web_view_request(self, web_view, web_frame):
    view = BrowserPage()
    self.new_tab(web_view = view)
    return view
		
  def _get_title(self, web_view):
    title = web_view.get_title()
    if not title:
      frame = web_view.get_main_frame()
      title = frame.props.title
      if not title:
        title = frame.get_uri()
    return title
    
  def _load_finished(self, web_view, frame, scrolled_window):
    scrolled_window.title = self._get_title(web_view)
    scrolled_window.url = frame.get_uri()
    if web_view.get_can_focus():
      web_view.grab_focus()
    
  def _title_changed(self, web_view, frame, title, scrolled_window):
    scrolled_window.title = title
    scrolled_window.url = frame.get_uri()
    self._update_title(scrolled_window)
    
  def _url_changed(self, web_view, frame, scrolled_window): 
    scrolled_window.title = self._get_title(web_view)
    scrolled_window.url = frame.get_uri()    
    self._update_title(scrolled_window)

  def _update_title(self, scrolled_window):
    label = self.get_tab_label(scrolled_window)
    label.label.set_label(scrolled_window.title) 
    if self.page_num(scrolled_window) == self.get_current_page():
      self._update_app(scrolled_window)
    
  def _update_app(self, scrolled_window):
    title, url = scrolled_window.title, scrolled_window.url
    self.emit('update-title', scrolled_window.get_child(), title, url)

class WebToolbar(gtk.Toolbar):

  __gsignals__ = {
    "go-back-requested": (gobject.SIGNAL_RUN_FIRST, gobject.TYPE_NONE, ()),
    "go-forward-requested": (gobject.SIGNAL_RUN_FIRST, gobject.TYPE_NONE, ()),
    "go-refresh-requested": (gobject.SIGNAL_RUN_FIRST, gobject.TYPE_NONE, ()),
    "go-home-requested": (gobject.SIGNAL_RUN_FIRST, gobject.TYPE_NONE, ()),
    "zoom-in-requested": (gobject.SIGNAL_RUN_FIRST, gobject.TYPE_NONE, ()),
    "zoom-out-requested": (gobject.SIGNAL_RUN_FIRST, gobject.TYPE_NONE, ()),
    "load-requested": (gobject.SIGNAL_RUN_FIRST, gobject.TYPE_NONE, (gobject.TYPE_STRING,)),
    "new-tab-requested": (gobject.SIGNAL_RUN_FIRST, gobject.TYPE_NONE, ())
  }

  def __init__(self, location_enabled=True, toolbar_enabled=True):
    gtk.Toolbar.__init__(self)

    self.set_style(gtk.TOOLBAR_ICONS)
    self.set_icon_size(gtk.ICON_SIZE_SMALL_TOOLBAR)

    self.back_button = gtk.ToolButton(gtk.STOCK_GO_BACK)
    self.forward_button = gtk.ToolButton(gtk.STOCK_GO_FORWARD)
    self.refresh_button = gtk.ToolButton(gtk.STOCK_REFRESH)
    self.home_button = gtk.ToolButton(gtk.STOCK_HOME)
    
    self.back_button.connect('clicked', lambda x: self.emit('go-back-requested'))
    self.forward_button.connect('clicked', lambda x: self.emit('go-forward-requested'))
    self.refresh_button.connect('clicked', lambda x: self.emit('go-refresh-requested'))
    self.home_button.connect('clicked', lambda x: self.emit('go-home-requested'))	
    
    self.add(self.back_button)
    self.add(self.forward_button)
    self.add(self.refresh_button)
    self.add(self.home_button)
  
    if True:
      self.add(gtk.SeparatorToolItem())
      self.entry = gtk.Entry()
      self.entry.connect('activate', lambda x: self.emit('load-requested', self.entry.props.text))
      entry_item = gtk.ToolItem()
      entry_item.set_expand(True)
      entry_item.add(self.entry)
      self.entry.show()
      self.insert(entry_item, -1)
      entry_item.show()
      
    self.add(gtk.SeparatorToolItem())
    self.zoom_in_button = gtk.ToolButton(gtk.STOCK_ZOOM_IN)
    self.zoom_out_button = gtk.ToolButton(gtk.STOCK_ZOOM_OUT)
    
    self.zoom_in_button.connect('clicked', lambda x: self.emit('zoom-in-requested'))
    self.zoom_out_button.connect('clicked', lambda x: self.emit('zoom-out-requested'))
 
    self.add(self.zoom_in_button)
    self.add(self.zoom_out_button)

    if True:
      self.add(gtk.SeparatorToolItem())
      self.addTabButton = gtk.ToolButton(gtk.STOCK_ADD)
      self.addTabButton.connect('clicked', lambda x: self.emit('new-tab-requested'))
      self.insert(self.addTabButton, -1)
      self.addTabButton.show()

class WebBrowser(gtk.Window):

  def __init__(self):
    gtk.Window.__init__(self)
    
    self.start_url = 'https://browser2-start.appspot.com/'
    
    self.toolbar = WebToolbar()
    self.content_tabs = ContentPane()
    
    self.content_tabs.connect('focus-entry', lambda x: self.toolbar.entry.grab_focus())
    self.content_tabs.connect('update-title', self._update_title)
    
    self.toolbar.connect('new-tab-requested', lambda x: self.content_tabs.new_tab(None, True))
    self.toolbar.connect('go-back-requested', lambda x: self.content_tabs.go_back())
    self.toolbar.connect('go-forward-requested', lambda x: self.content_tabs.go_forward())
    self.toolbar.connect('go-refresh-requested', lambda x: self.content_tabs.refresh())
    self.toolbar.connect('go-home-requested', lambda x: self.content_tabs.load(self.start_url))
    self.toolbar.connect('zoom-in-requested', lambda x: self.content_tabs.zoom_in())
    self.toolbar.connect('zoom-out-requested', lambda x: self.content_tabs.zoom_out())
    self.toolbar.connect('load-requested', self.load_requested)

    vbox = gtk.VBox(spacing = 0)
    vbox.pack_start(self.toolbar, expand = False, fill = False)
    vbox.pack_start(self.content_tabs, expand = True, fill = True)
    self.add(vbox)
    self.connect('destroy', self.quit)
    self.connect('key-press-event', self._key_pressed)
    self.set_default_size(800, 600)
    
    self.show_all()
    self.content_tabs.new_tab(self.start_url, True)
    
  def quit(self, window):
    num_pages = self.content_tabs.get_n_pages()
    while num_pages != -1:
      scrolled_window = self.content_tabs.get_nth_page(num_pages)
      if scrolled_window:
        web_view = scrolled_window.get_child()
        web_view.destroy()
      num_pages = num_pages - 1
    self.destroy()
    gtk.main_quit()
    
  def load_requested(self, entry, text):
    if not text:
      return
    try:
      text.index("://")
    except:
      if (' ' in text and '/' not in text) or ('.' not in text):
        text = 'https://www.google.si/search?q=' + text
      else:
        text = "http://" + text
    self.content_tabs.load(text)  
    
  def _update_title(self, notebook, web_view, title, url):
    if not title is None:
      self.set_title(_("%s") % title)
    if not url is None:
      self.toolbar.entry.set_text(url)
    self.toolbar.back_button.set_sensitive(web_view.can_go_back())
    self.toolbar.forward_button.set_sensitive(web_view.can_go_forward())
    
  def _key_pressed(self, widget, event):
    mapping = {
     'r': self.content_tabs.refresh,
     'w': self.content_tabs.close_current_tab,
     't': self.content_tabs.new_tab,
     'l': self.toolbar.entry.grab_focus
    }
    if event.state & gtk.gdk.CONTROL_MASK and gtk.gdk.keyval_name(event.keyval).lower() in mapping:
      mapping[gtk.gdk.keyval_name(event.keyval)]()
    elif event.state & gtk.gdk.MOD1_MASK:
      if gtk.gdk.keyval_name(event.keyval) == 'F4':
		self.quit(self)

def returntrue(*args):
  return True
  
if __name__ == "__main__":
  webbrowser = WebBrowser()
  gtk.main()

